from sqlalchemy import text
from src.core.logic.canonical_exporter import CanonicalDataExporter

def check_titles():
    exporter = CanonicalDataExporter(sink=None)
    session = exporter.initiative_ctrl._service._repository._session
    
    titles_to_check = [
        "INSPEÇÃO EM CADEIAS DE ISOLADORES DE VIDRO EM LINHAS DE TRANSMISSÃO DE 345KV UTILIZANDO INTELIGÊNCIA ARTIFICIAL",
        "IMPACT OF SYNTHETIC DATA GENERATED BY A BETA-VARIATIONAL AUTOENCODER ON SPEECH EMOTION RECOGNITION",
        "CÁLCULO DE EMPENO EM PLACAS DE AÇO UTILIZANDO VISÃO COMPUTACIONAL",
        "SUPERVISÃO E CONTROLE DE NÍVEL COM LÓGICA FUZZY: UMA INTEGRAÇÃO BASEADA EM OPC",
        "Análise de Sinais EEG em Pacientes Pós-AVC com Conditional Variational Autoencoder e Redução Dimensional via UMAP"
    ]
    
    print(f"{'Title (matches)':<60} | {'Found?':<10} | {'Type':<20}")
    print("-" * 100)
    
    for t in titles_to_check:
        # Use LOWER() for case-insensitive match in SQLite
        # JOIN with initiatives to access 'name' column
        query = text("""
            SELECT a.id, a.type 
            FROM advisorships a
            JOIN initiatives i ON a.id = i.id
            WHERE LOWER(i.name) = LOWER(:t)
        """)
        res = session.execute(query, {"t": t}).fetchone()
        
        found = "YES" if res else "NO"
        adv_type = res[1] if res else "N/A"
        
        print(f"{t[:57]+'...':<60} | {found:<10} | {adv_type:<20}")

if __name__ == "__main__":
    check_titles()
